### ISSUE TITLE
Append reactive navigation to assistive rehab exercises

### ISSUE THREAD

**Issue by pattacini** [robotology/assistive-rehab#155]
It would be nice if the robot could do the following:
- [x] First, it presents the exercise to the human.
- [x] Second, it keeps on showing the exercise while gauging the human performance.
- [ ] **Third**, it stops showing the exercises but keeps monitoring the human. At the same time, the robot will "slightly" navigate in an area in front of the human.

With regards to point 3, navigation will be merely reactive (i.e. no map employed) so that obstacles (e.g. skeletons, walls) are considered but no self-location will be carried out. Further, if the human performs poorly, the robot can get closer and point to the body part involved in the assessment.

**Comment by pattacini** [comment]
We discovered that producing skeleton information at 10 Hz can be quite limiting in terms of keeping the target in sight, given the narrow field of view of the Realsense plus the dynamics of the robot's head.

**Comment by pattacini** [comment]
To improve the performance we might want to explore the possibility to have feed-forward compensation of the velocity of the base (the odometry is provided by the `baseController` module) at the gaze control level.

**Comment by vvasco** [comment]
Apart from `yarpOpenPose` which runs at 10 Hz, It would be nice to understand if other components in the skeleton pipeline add latency to the pipeline.

**Comment by vvasco** [comment]
> Apart from `yarpOpenPose` which runs at 10 Hz, It would be nice to understand if other components in the skeleton pipeline add latency to the pipeline.

Done in #166.
