### ISSUE TITLE
TT to the lab/community

### ISSUE THREAD

**Issue by pattacini** [robotology/assistive-rehab#162]
It would be cool to do some kind of tech transfer ⚙️ to the lab about the methods and/or tools we used.

A possible unordered list of things:
- Dynamic Time Warping
- Action Recognition
- Plot.ly
- Skeletons

The frame could be the [**Researcher of the Week**][1] 👩‍🔬 😉 

[1]: https://spectrum.chat/icub/researcher-week

**Comment by vvasco** [comment]
Planned on April, 2nd

**Comment by pattacini** [comment]
It was super sweet 🥇
