### ISSUE TITLE
Buy a walking stick

### ISSUE THREAD

**Issue by pattacini** [robotology/assistive-rehab#176]
We need to buy a walking stick to proceed with the evaluation relative to the TUG test.
See #173.

**Comment by vtikha** [comment]
I have one at home that I can bring. No need to buy anything, it is like this [one](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiZlJ-5vafhAhWM6qQKHbVIBRYQjRx6BAgBEAU&url=https%3A%2F%2Fit.aliexpress.com%2Fitem%2FWenge-wood-walking-stick-old-age-pukou-birthday-gifts-hiking-pole-engraving-crafts%2F32365238390.html&psig=AOvVaw0YuwkoZUWSDmUxc4qHVk0T&ust=1553953324745072).

**Comment by pattacini** [comment]
Awesome! We got a deal 😄 
Thanks!

**Comment by vvasco** [comment]
I have the stick now, thanks @vtikha !

**Comment by pattacini** [comment]
Yeah!
