### ISSUE TITLE
Assess the impact of a walking stick onto OpenPose

### ISSUE THREAD

**Issue by pattacini** [robotology/assistive-rehab#177]
Accurately verify whether a person walking with the aid of a stick could impair somehow OpenPose in detecting body parts.

**Comment by vvasco** [comment]
OpenPose is very robust to walking sticks! The following figures show the output of `yarpOpenPose` in several scenarios, of increasing difficulty.

### Walking naturally with a walking stick
The skeleton is very robustly detected and never confused with the stick:
![w1](https://user-images.githubusercontent.com/9716288/55465588-ba2b5680-55fd-11e9-8c58-1622e44c8c03.gif)

### Stick very close to the leg and partially occluding it
The skeleton is impressively robust and the right leg's keypoints get never confused with the stick!
![w2](https://user-images.githubusercontent.com/9716288/55465613-cd3e2680-55fd-11e9-839b-246956532ba6.gif)

### One foot not visible
In this scenario, the right foot is not visible and the walking stick might be easily detected as part of the leg.
We can see that the ankle keypoint is detected even if not visible. However this is not dependent on the stick, as the ankle keypoint is still detected even when the stick is moved far from the leg. 
![w3](https://user-images.githubusercontent.com/9716288/55465625-d202da80-55fd-11e9-8535-a4a73fc99f66.gif)

I think that OpenPose is very robust for the walking tests considered in our scenarios ([TUG](#173), 10MWT, 6MWT). The last scenario was reported to evaluate the potential of OpenPose in very challenging situations, but is unlikely to occur in the mentioned walking tests.

**Comment by pattacini** [comment]
Nicely done!
