### ISSUE TITLE
Evaluate the 3D projection of the foot keypoint

### ISSUE THREAD

**Issue by vvasco** [robotology/assistive-rehab#183]
Given the foot estimation in 2D seems accurate (#179), we want to accurately evaluate if the 3D projection impairs somehow the estimation.

**Comment by vvasco** [comment]
Projecting the 2D keypoints in 3D using a filtered depth map provides this output:
 
<img src="https://user-images.githubusercontent.com/9716288/56025541-9e693400-5d12-11e9-9467-e95ea24de3f8.gif" width=400 height=600/>

Feet appear quite stable even in 3D.

**Comment by pattacini** [comment]
It may be beneficial to drop in here an archive containing the scripts used for this analysis.

**Comment by vvasco** [comment]
Here it is:
[visualize_3d_foot.zip](https://github.com/robotology/assistive-rehab/files/3079010/visualize_3d_foot.zip)
