### ISSUE TITLE
Extend yarpOpenPose to include feet

### ISSUE THREAD

**Issue by vvasco** [robotology/assistive-rehab#184]
Given #179, we want to extend `yarpOpenPose` to include feet keypoints.
It would be also good to have a switch to disable feet.

**Comment by vtikha** [comment]
I have just merged the new version of [yarpOpenPose](https://github.com/robotology/human-sensing/pull/16/commits) that includes the new changes of openpose. I will leave this issue under review for a couple of days for testing and then will close it. 

@vvasco @pattacini

**Comment by pattacini** [comment]
Super cool 🚀

**Comment by vtikha** [comment]
putting it back `in progress` as it occurred to me that it needs a quick modification 🤔

**Comment by vtikha** [comment]
all fixed as of [this commit](https://github.com/robotology/human-sensing/commit/43064f481e84b41238270da060349d7dc2bc2315). The part list is now sent correctly through the output port

**Comment by vtikha** [comment]
I am closing this for now.
