### ISSUE TITLE
Update motionAnalyzer to evaluate TUG metrics

### ISSUE THREAD

**Issue by vvasco** [robotology/assistive-rehab#190]
The `motionAnalyzer` has to be updated in order to extract online metrics related to the TUG, such as:
- **time spent** to perform the test;
- **range of motion** of the lower limbs;
- **step length** and **step width**;
- **walking speed**.

`motionAnalyzer` has to be carefully tested and, **importantly**, has to be compatible with the demo [Y2M2](https://github.com/robotology/assistive-rehab#workspaces/assistive-rehab-5abdf5acc357d36113ef6d4e/reports/burndown?milestoneId=3959591).

**Comment by pattacini** [comment]
Done in #204.
