### ISSUE TITLE
Provide S4HRI with the movement 

### ISSUE THREAD

**Issue by pattacini** [robotology/assistive-rehab#196]
We need to provide information regarding the movement performed by R1.

**Comment by vvasco** [comment]
Here there are the movements:
- **abduction**:
    <img src="https://user-images.githubusercontent.com/9716288/57623834-ea68fc00-7590-11e9-9a9f-054bb50eb00c.gif" width=400>

- **internal rotation**:
     <img src="https://user-images.githubusercontent.com/9716288/57623935-22703f00-7591-11e9-9a3e-ad3d4bd897c6.gif" width=400>

- **external rotation**
     <img src="https://user-images.githubusercontent.com/9716288/57623978-3ae05980-7591-11e9-958a-82c0e544490f.gif" width=400>

cc @ddetommaso @PCH313
