### ISSUE TITLE
Deal with the panel occluding robot's arm

### ISSUE THREAD

**Issue by pattacini** [robotology/assistive-rehab#198]
Through a YARP port we need to let the system know that the "occlusion" has been added to the experiment so that the robot will stop giving feedback.

This feature will be available both in SAR and VA mode.

**Comment by vvasco** [comment]
Done in `feat/virtual-robot`.

**Comment by vvasco** [comment]
Hi @ddetommaso @PHC313, we have a question about the panel. How should we deal with it during an experiment with the real robot? Should we add it __during__ the exercise or you foresee two __different sessions__ (training without the panel + training with the panel?)

**Comment by ddetommaso** [comment]
Hi @vvasco, 
based on our originally idea the panels should be present in a different session of the experiment, but I would ask @PCH313 and @CescoWillemse to take care of the design of the sudy in #203

**Comment by vvasco** [comment]
Thanks @ddetommaso
