### ISSUE TITLE
Get aligned with S4HRI for the YARP port-based API 

### ISSUE THREAD

**Issue by pattacini** [robotology/assistive-rehab#199]
We need to pass on S4HRI the information regarding how to control the demo via YARP ports.
It may be that extensions to the present commands are required.

This is fundamental to synchronize data collected from EEG.

**Comment by vvasco** [comment]
Instructions for running the demo can be found in #193. Please note that the code is available in the the branch **`feat/virtual-robot`**.
The interaction is controlled through the rpc port `/interactionManager/cmd:rpc`, with the following commands:
- `start`: to start the interaction;
- `start_occlusion`: to introduce a panel occluding the arm and stopping the feedback;
- `stop`: to stop the interaction.

Note: the number of repetitions of the exercise is controlled by the parameter `nrep-perform` in the `interactionManager`, which is set to 7 by default. We need to check how high this can be pushed on the real robot.

cc @ddetommaso @PCH313
