### ISSUE TITLE
Write tutorial on simulated experiment

### ISSUE THREAD

**Issue by pattacini** [robotology/assistive-rehab#201]
Following up the completion of #193, it'd be great to provide the corresponding tutorial from within our documentation.

I'd expand on the instructions already given in #193, indeed.

Two more considerations:
- Adding up an **animated GIF** is a bonus
- Write up the tutorial as all the involved branches would have been merged

**Comment by vvasco** [comment]
The tutorial can be found [here](https://robotology.github.io/assistive-rehab/doc/mkdocs/site/virtual_demo/).
