### ISSUE TITLE
Include moving human models in gazebo

### ISSUE THREAD

**Issue by vvasco** [robotology/assistive-rehab#202]
It would be beneficial to include human models in `Gazebo` to simulate the exercise session and perform debugging.
Examples of _static_ human models can be found [here](https://github.com/valegagge/humanModels). We would need to animate the model, an example can be found [here](http://gazebosim.org/tutorials?tut=actor).

**Comment by pattacini** [comment]
I think we can close it as we're no longer aiming at it.
