### ISSUE TITLE
Design Experiment 1 Train With Me (S4HRI)

### ISSUE THREAD

**Issue by ddetommaso** [robotology/assistive-rehab#203]
In order to implement the psychological study (general protocol [here](https://docs.google.com/document/d/1o2umAve-6E37HXf0ruSC6F4c3wGwrv2vbxSRGYfnyq8/edit#heading=h.p1f0s4700s4a)), the experimenters need to provide to the developers the complete design of the experiment (virtual and real modes) consisting of:

- [x] Experimental hypothesis, nr of trials, conditions, ...
- [x] Experimental setup (robot and participant positions, distances, light conditions,..)
- [x] Trial structure (the tasks composing the single trial of the study)
- [x] Physiological measures on participants, robot data, ...

**Comment by PCH313** [comment]
* [-]  Experimental hypothesis, nr of trials, conditions, ...
Experimental hypothesis: Embodiment of the robot (physical/virtual) has an influence on the performance in the task and engagement 
Two conditions: Robot; Virtual agent 
Six blocks of 3 Phases (observation, imitation, occlusion)

* [ ]  Experimental setup (robot and participant positions, distances, light conditions,..)
To be determine on site 

* [-]  Trial structure (the tasks composing the single trial of the study)
Six blocks of 3 Phases (observation, imitation, occlusion)
12 movements by phase 

* [-]  Physiological measures on participants, robot data, ...
See Cesco's document
