### ISSUE TITLE
Gazebo models of objects for hospital environments

### ISSUE THREAD

**Issue by pattacini** [robotology/assistive-rehab#233]
If we might need in the future: https://app.ignitionrobotics.org/openrobotics/fuel/collections/Hospital.
Thanks @traversaro for pointing this out.

**Comment by traversaro** [comment]
Note that if you are using Gazebo 10, it should be possible to just include directly the models in your `.world` files, without the need to manually download them locally, for example for https://app.ignitionrobotics.org/openrobotics/fuel/models/VisitorChair you need to add: 
~~~
<include>
<uri>
https://fuel.ignitionrobotics.org/1.0/openrobotics/models/VisitorChair
</uri>
</include>
~~~

 If  Gazebo is running on a machine connected to the Internet, when you launch the world it will automatically download and use the model. Clearly if you want to make sure that your simulation runs also if you have no internet connectivity or the Ignition Fuel server is down, you may prefer to download the models locally.
