### ISSUE TITLE
Adjust skeleton poses due to filtered depth

### ISSUE THREAD

**Issue by pattacini** [robotology/assistive-rehab#234]
Once we have the skeletons retrieved from the filtered depth, we need to compensate for the incorrect depth by applying a kind of unwarping in order to adjust the skeleton pose.

**Comment by pattacini** [comment]
It came out that with the following parameters, the filtered depth gives us skeletons with the correct metrics:
```ini
[depth]
enable                      true
kernel-size                 10
iterations                  5
min-distance                0.5
max-distance                10.0
```
| |
|:---:|
| Skeletons with unfiltered depth |
| ![no-filtering][1] |
| Skeletons with filtered depth |
| ![filtering][2] |

Thus, @vvasco could you please try out the options above within TUG experiments and report here any findings?

[1]: https://user-images.githubusercontent.com/3738070/68116447-25723980-fefb-11e9-9d3c-64afafef4364.gif
[2]: https://user-images.githubusercontent.com/3738070/68116462-315dfb80-fefb-11e9-897d-dbfdce7ae290.gif

**Comment by vvasco** [comment]
With the following parameters:

```
[depth]
enable                      true
kernel-size                 4
iterations                  3
min-distance                0.5
max-distance                10.0
```

I obtained the following result:

![ezgif com-optimize](https://user-images.githubusercontent.com/9716288/68573642-6cff4500-0468-11ea-86e8-2aadfbd39d69.gif)

The ankles look reasonably close to the lines when I stand on them. I checked the metric I use for line crossing and it works out with these parameters.

**Comment by pattacini** [comment]
Awesome! Let's go this way then ✨ 
Could you please put those parameters in `master` for the TUG?

**Comment by vvasco** [comment]
Sure!

**Comment by pattacini** [comment]
Soon afterward, please close this issue with a pointer to the commit hash.

**Comment by vvasco** [comment]
Done here c86e3b69e054939a6fa9b00498ded711acf04952
