### ISSUE TITLE
Improve feedback modality

### ISSUE THREAD

**Issue by vvasco** [robotology/assistive-rehab#247]
The current feedback provided to the user in response to a question like "How good am I in doing this?" is only based on the time spent for completing the test. 
This could be improved including the speed of the person and the distance from the line.

**Comment by vvasco** [comment]
This is currently developed in the `feat/improve-feedback` branch, but I'm unable to test it as it requires to ask questions during the exercise and this is not feasible now with the hand-on triggering option (the robot focuses on the lower part of the body and cannot see the hand on). 
I'll test this after #261.

**Comment by pattacini** [comment]
This issue is now unblocked.
