### ISSUE TITLE
Release v0.5.0

### ISSUE THREAD

**Issue by pattacini** [robotology/assistive-rehab#259]
At a certain point, we should be ready to release v0.5.0 😉 and update the documentation, possibly with some tutorials and/or high-level explanations of the TUG.

**Comment by pattacini** [comment]
Done!

**Comment by vvasco** [comment]
The release can be found [here](https://github.com/robotology/assistive-rehab/releases/tag/v0.5.0) at cd4da866b4d769cea1c3a2b155561b8337911095.
