### ISSUE TITLE
Replicate TUG in simulation

### ISSUE THREAD

**Issue by vvasco** [robotology/assistive-rehab#267]
Replicating TUG in simulation would be a powerful tool allowing us to _debug_ and _systematically test_ current / new features.

**Comment by pattacini** [comment]
Amazing achievement @vvasco 🥇

**Comment by pattacini** [comment]
A very nice post on this appeared on Spectrum at https://spectrum.chat/icub/research-news/the-timed-up-and-go-tug-with-r1~776cc44a-cf19-4ca6-96d1-7d604caa6593.
