### ISSUE TITLE
CI fails because of `curl` build error

### ISSUE THREAD

**Issue by pattacini** [robotology/assistive-rehab#304]
Opened issue upstream: https://github.com/microsoft/vcpkg/issues/23874.

**Comment by pattacini** [comment]
@traversaro gave https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/pull/51 another whirl. If successful, we will be able to update vcpkg.

**Comment by pattacini** [comment]
The attempt came off well; we're now yielding a new release.

**Comment by traversaro** [comment]
> The attempt came off well; we're now yielding a new release.

Release where the new archive will be uploaded: https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/releases/tag/v0.8.0 .
Job that is producing the archive: https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/actions/runs/2161357833 .

**Comment by pattacini** [comment]
Everything works fine again as in https://github.com/robotology/assistive-rehab/actions/runs/2165904817.

Thanks heaps @traversaro!
