### ISSUE TITLE
References for 6MWT and 10MWT

### ISSUE THREAD

**Issue by pattacini** [robotology/assistive-rehab#69]
https://github.com/spencer-project/spencer_people_tracking.

**Comment by pattacini** [comment]
Somewhat related resources we might want to explore: https://github.com/spencer-project/spencer_people_tracking.

**Comment by vvasco** [comment]
SPENCER was a EU project (finished in 2016) with the aim of developing algorithms for service robots that can guide groups of people through highly dynamic and crowded pedestrian environments.

The people tracker developed within this project includes the following steps:
- **motion prediction**: for each detected person, motion is predicted using an Extended Kalman filter. To deal with dynamic environments, a bank of first and second order motion models is used and combined in an Interacting Multiple Models filter (IMM);
- **data association**: new incoming detections are associated with existing tracks using the Nearest-Neighbor (NN), which selects the track minimizing the distance between detection and prediction;

A _track initiation logic_ is also included, which confirms a set of detections to be a track if:
- its speed is restricted to a pre-defined interval `[v_min,v_max]`
- the Euclidean distance between the current detection and the prediction of the track candidate is below a threshold.

This [video](https://www.youtube.com/watch?v=r2fGCrekGj8) shows the result of the tracking on a mobile platform in a real crowded environment (airport). The scenario is rather complex, extremely dynamic and the tracker seems to work well (note: detections are obtained with both RGB-D sensors and 2D laser range sensors), with low CPU consumption (less than 10% of a single i7 Core).

We might rely on a similar strategy for dealing with distractors (in the case of 6MWT, people not relevant for the test can walk throughout the corridor). From our previous analysis (#171), data appear consistent to apply a NN strategy.

[Resource](https://www.semanticscholar.org/paper/Towards-a-Robust-People-Tracking-Framework-for-in-%2C-Linder-Girrbach/300b819bbbe857f5fe89d0895f907073fc288719)
