### ISSUE TITLE
Creating fake template skeletons instead of recording from humans repetitions

### ISSUE THREAD

**Issue by vvasco** [robotology/assistive-rehab#98]
We want to create fake skeletons to use as template for testing the new feedback system.
These would be included in the pipeline and could eventually replace the current templates (that we have registered) not only for testing, but also as new templates.

This would give us more control on the template and avoid situations in which the real movement is hard to reproduce (for example current templates for internal/external rotation include the movement of the elbow, which, instead, is supposed to be steady).

**Comment by pattacini** [comment]
Implemented in #213.
